{
    'name': 'Barcode Customization',
    "version": "15.0.0.0.0",
    'author': '',
    'website': '',
    'license': 'LGPL-3',
    'installable': True,
    'summary': 'Barcode Customization',
    'depends': [
        'base',
        'stock',
        'stock_barcode',
        'product_expiry',
        'inventory_customization',
        'mdgportal_sync',
        'stock_barcode_picking_batch',
    ],
    'data': [
             'views/stock_barcode_view.xml',
             'views/stock_expiration_date.xml',
             'views/stock_view.xml',
             'views/production_lot_view.xml',
             'views/stock_move_line.xml',
             'views/stock_picking_view.xml',
             # 'views/stock_inventory_view.xml',
    ],

    'assets': {
            'web.assets_backend': [
                'stock_barcode_customization/static/src/components/stock_barcode_main.js',
                'stock_barcode_customization/static/src/components/stock_barcode_dest_main.js',
                'stock_barcode_customization/static/src/widgets/set_bigger_uom_button.js',
                'stock_barcode_customization/static/src/widgets/set_bigger_uom_button.scss',
                'stock_barcode_customization/static/src/models/stock_barcode_model.js',
                'stock_barcode_customization/static/src/models/stock_barcode_picking_model.js',
                'stock_barcode_customization/static/src/models/stock_barcode_picking_model_pkg.js',
                # 'stock_barcode_customization/static/src/widgets/digipad.js',
                'stock_barcode_customization/static/src/scss/stock_barcode.scss',
                'stock_barcode_customization/static/src/components/line.js',
                'stock_barcode_customization/static/src/components/line.scss',
                # 'stock_barcode_customization/static/src/js/stock_barcode_view.js',
                # 'stock_barcode_customization/static/src/widgets/check_product.js',
                'stock_barcode_customization/static/src/components/grouped_line.js',
                'stock_barcode_customization/static/src/components/main.js',
                'stock_barcode_customization/static/src/stock_barcode_menu.js',
            ],
            'web.assets_qweb': [
                # 'stock_barcode_customization/static/src/**/*.xml',
                'stock_barcode_customization/static/src/widgets/set_bigger_uom_button.xml',
                # 'stock_barcode_customization/static/src/widgets/digipad.xml',
                'stock_barcode_customization/static/src/components/line.xml',
                # 'stock_barcode_customization/static/src/widgets/check_product.xml',
                'stock_barcode_customization/static/src/components/grouped_line.xml',
                'stock_barcode_customization/static/src/stock_barcode_menu.xml',
            ],
        }
}
