from . import stock_autoallocate
from . import product_template
from . import stock_picking
#from . import stock_rule
from . import zone_location
from . import stock_location
from . import product
from . import sale_order_line
from . import purchase_order
from . import product_principle
from . import stock_quant_package